### ISSUE TITLE
Confusing parameters in Transmission

### ISSUE THREAD

**Issue by davidosterberg** [efirvida/python-gearbox#3]
In the transmission class the parameters are quite confusing

```
transmission = Transmission(
    gears=pair,
    lubricant=lubricant,
    rpm_in=1450.0,
    rpm_out=243.5,            # Why is this not calculated automatically from rpm_in?
    n=40.0,                   # This should be called P according to the ISO standard
    l=10000.0,
    gear_box_type=2,
    ka=1.3,
    sh_min=1,
    sf_min=1
)
```

I propose to rename _n_ to _P_, and to remove the _rpm_out_ parameter.

**Comment by efirvida** [comment]
thanks for your suggestions, and contributions I agree with changing P, I'm also working on new version with more clear names, because I mix names between ISO and AGMA. but it will take some time to finish, so feel free to change it.

the purpose os rpm_out, its more like "desired rpm out" for the case if you are designing a gearbox, you will have design  needs of input and output rpm, but sometimes you can't find the correct gear tooth combination, so you will have certain %error between needs and real, that's the only propose of that.
